export const DATA = {
    order: [
        "purples",
        "blues",
        "greens",
        "yellows",
        "oranges",
        "reds",
        "pinks",
        "browns",
        "greys",
        "whites",
        "blacks",
    ],
    labels: {
        purples: "Purples",
        blues: "Blues",
        greens: "Greens",
        yellows: "Yellows",
        oranges: "Oranges",
        reds: "Reds",
        pinks: "Pinks",
        browns: "Browns",
        greys: "Greys",
        whites: "Whites",
        blacks: "Blacks",
    },
    families: {
        purples: [
            { name: "dark purple", hex: "#201c3b" },
            { name: "smoke purple", hex: "#7863a9" },
            { name: "purple", hex: "#854cc7" },
            { name: "lilac", hex: "#aa71f4" },
            { name: "violet", hex: "#b469ff" },
            { name: "lavender", hex: "#be86f7" },
            { name: "mauve", hex: "#947be0" },
            { name: "boysenberry", hex: "#c180db" },
            { name: "plum", hex: "#a278d9" },
            { name: "grape", hex: "#d57ae1" },
            { name: "periwinkle mist", hex: "#af70d8" },
            { name: "iris", hex: "#9a7cdc" },
            { name: "orchid", hex: "#c263dd" },
            { name: "amethyst", hex: "#a774db" },
            { name: "eggplant", hex: "#d160d6" },
            { name: "wine", hex: "#b866df" },
            { name: "mulberry", hex: "#8958d5" },
            { name: "raisin", hex: "#c764d9" },
            { name: "heather", hex: "#9b4adb" },
            { name: "thistle", hex: "#7e5cd8" },
            { name: "wisteria", hex: "#af48d4" },
            { name: "byzantium", hex: "#8e4ddd" },
            { name: "tyrian", hex: "#c740d3" },
            { name: "grape soda", hex: "#6a30da" },
            { name: "royal purple", hex: "#a34bd6", nav: true },
            { name: "ube", hex: "#b943d6" },
            { name: "mountbatten", hex: "#842fd2" },
            { name: "pomp", hex: "#da33dc" },
            { name: "pansy", hex: "#9c2bcd" },
            { name: "african violet", hex: "#7532d5" },
            { name: "electric purple", hex: "#b821ce" },
            { name: "veronica", hex: "#8e2ad3" },
            { name: "phlox", hex: "#5426c0" },
            { name: "dark orchid", hex: "#aa20d4" },
            { name: "purple heart", hex: "#6b23ba" },
            { name: "medium purple", hex: "#bd25c7" },
            { name: "fandango", hex: "#831ab9" },
            { name: "mardi gras", hex: "#5d22c0" },
            { name: "dark magenta", hex: "#941eac" },
            { name: "imperial", hex: "#741bbe" },
            { name: "regalia", hex: "#401ca5" },
            { name: "russian violet", hex: "#891eb3" },
            { name: "persian indigo", hex: "#5417a1" },
            { name: "tekhelet", hex: "#9d1cac" },
            { name: "majorelle", hex: "#661898" },
            { name: "blue violet", hex: "#4718a7" },
            { name: "han purple", hex: "#771691" },
            { name: "violet blue", hex: "#5b179e" },
            { name: "xanadu", hex: "#86148a" },
            { name: "glossy grape", hex: "#6e1697" },
        ],
        blues: [
            { name: "night sky", hex: "#051626" },
            { name: "galaxy blue", hex: "#001122" },
            { name: "dark blue", hex: "#101628" },
            { name: "midnight blue", hex: "#0d1b2f" },
            { name: "navy", hex: "#112038" },
            { name: "indigo", hex: "#172741" },
            { name: "graphite", hex: "#141a2e" },
            { name: "dark teal", hex: "#182626" },
            { name: "dark slate", hex: "#3b4261" },
            { name: "slate", hex: "#586e98" },
            { name: "smoke", hex: "#737aa2" },
            { name: "stone", hex: "#5d82be" },
            { name: "denim", hex: "#4673bc" },
            { name: "periwinkle", hex: "#7aa2f7" },
            { name: "cobalt", hex: "#5aa8ff" },
            { name: "ocean", hex: "#4da0ff" },
            { name: "sky blue", hex: "#00aeff" },
            { name: "arctic", hex: "#7dcfff" },
            { name: "cyan", hex: "#66d4ff" },
            { name: "bright cyan", hex: "#00d7ff" },
            { name: "teal", hex: "#2ac3de" },
            { name: "aqua", hex: "#0db9d7" },
            { name: "jade", hex: "#26a1ba" },
            { name: "aquamarine", hex: "#00fbee" },
            { name: "azure", hex: "#4685ff", nav: true },
            { name: "mint", hex: "#2fe1c8" },
            { name: "cerulean", hex: "#82cbe3" },
            { name: "sapphire", hex: "#869fdf" },
            { name: "peacock", hex: "#78b1dc" },
            { name: "lapis", hex: "#7b86e4" },
            { name: "spruce", hex: "#6996db" },
            { name: "admiral", hex: "#70bbde" },
            { name: "cornflower", hex: "#5372e0" },
            { name: "steel blue", hex: "#619fdc" },
            { name: "powder blue", hex: "#494fd9" },
            { name: "baby blue", hex: "#4b7ce2" },
            { name: "cadet", hex: "#399bd8" },
            { name: "prussian", hex: "#4158db" },
            { name: "cobalt deep", hex: "#2074df" },
            { name: "electric blue", hex: "#30acdb" },
            { name: "royal blue", hex: "#234fcc" },
            { name: "denim wash", hex: "#1b86df" },
            { name: "cerulean frost", hex: "#1e2bc0" },
            { name: "yale blue", hex: "#1e5ecb" },
            { name: "air force", hex: "#1580b9" },
            { name: "glaucous", hex: "#1a3abe" },
            { name: "tufts blue", hex: "#165ba7" },
            { name: "celestial", hex: "#1416b3" },
            { name: "bleu de france", hex: "#123b9a" },
            { name: "iceberg", hex: "#1268a4" },
        ],
        greens: [
            { name: "neon mint", hex: "#00ffaf" },
            { name: "lime", hex: "#7dfb89" },
            { name: "lime neon", hex: "#65ff74" },
            { name: "chartreuse", hex: "#a8d766" },
            { name: "lime zest", hex: "#6bd174" },
            { name: "spring green", hex: "#88d065" },
            { name: "kelly green", hex: "#64d88c" },
            { name: "forest", hex: "#66cf5e" },
            { name: "emerald", hex: "#9cd368" },
            { name: "jade green", hex: "#51d569" },
            { name: "pine", hex: "#7bd261" },
            { name: "sage", hex: "#50ce87" },
            { name: "olive drab", hex: "#54d857" },
            { name: "fern", hex: "#7ccd49" },
            { name: "moss", hex: "#53d177" },
            { name: "shamrock", hex: "#4fd43b" },
            { name: "malachite", hex: "#94d04c" },
            { name: "viridian", hex: "#3bcd4d" },
            { name: "seafoam", hex: "#6ad73e" },
            { name: "mint green", hex: "#34cc6d" },
            { name: "pistachio", hex: "#43d03e" },
            { name: "avocado", hex: "#74d029" },
            { name: "hunter green", hex: "#36cf58" },
            { name: "juniper", hex: "#4ac32e" },
            { name: "basil", hex: "#28d67b", nav: true },
            { name: "clover", hex: "#2bbe34" },
            { name: "laurel", hex: "#64ca2d" },
            { name: "celadon", hex: "#22c054" },
            { name: "tea green", hex: "#39c52a" },
            { name: "mantis", hex: "#6eb426" },
            { name: "harlequin", hex: "#21c73c" },
            { name: "screamin green", hex: "#47af24" },
            { name: "neon green", hex: "#25bb64" },
            { name: "june bud", hex: "#1bb01c" },
            { name: "asparagus", hex: "#5fb623" },
            { name: "artichoke", hex: "#1fa442" },
            { name: "dartmouth", hex: "#33b71b" },
            { name: "brunswick", hex: "#679f1d" },
            { name: "castleton", hex: "#1fab2d" },
            { name: "myrtle", hex: "#419e17" },
            { name: "phthalo green", hex: "#1da54d" },
            { name: "hooker green", hex: "#209419" },
            { name: "jungle green", hex: "#59a317" },
            { name: "army green", hex: "#178e2f" },
            { name: "dark moss", hex: "#359a19" },
            { name: "reseda", hex: "#148a49" },
            { name: "laurel wreath", hex: "#17951c" },
            { name: "bottle green", hex: "#3d8314" },
            { name: "feldgrau green", hex: "#148f39" },
            { name: "sacramento", hex: "#1e7d12" },
        ],
        yellows: [
            { name: "gold", hex: "#fec339" },
            { name: "sun", hex: "#fd971f" },
            { name: "lemon", hex: "#f2d287" },
            { name: "canary", hex: "#eee18b" },
            { name: "mustard", hex: "#eed587" },
            { name: "amber", hex: "#f3eb87" },
            { name: "honey", hex: "#eedb82" },
            { name: "daffodil", hex: "#efd389" },
            { name: "goldenrod", hex: "#f2e579" },
            { name: "corn", hex: "#efd885" },
            { name: "butter", hex: "#eee878" },
            { name: "dandelion", hex: "#f3e17c" },
            { name: "flax", hex: "#eecf74" },
            { name: "maize", hex: "#efe57b" },
            { name: "saffron", hex: "#f3d96a" },
            { name: "chrome yellow", hex: "#efcc76" },
            { name: "cadmium yellow", hex: "#eedd6a" },
            { name: "school bus", hex: "#f4d56d" },
            { name: "banana", hex: "#eee665" },
            { name: "cream yellow", hex: "#efda6d" },
            { name: "citrine", hex: "#f4cb5b" },
            { name: "jonquil", hex: "#f0e268" },
            { name: "xanthous", hex: "#efd15b" },
            { name: "mikado", hex: "#f5ef5e" },
            { name: "aureolin", hex: "#efd956", nav: true },
            { name: "naples yellow", hex: "#f0cd5e" },
            { name: "straw", hex: "#f5e84b" },
            { name: "sunglow", hex: "#f0d559" },
            { name: "icterine", hex: "#f0c14c" },
            { name: "hansa", hex: "#f6e34e" },
            { name: "meat brown", hex: "#f0cb47" },
            { name: "arylide", hex: "#f1e84e" },
            { name: "trombone", hex: "#f6d93b" },
            { name: "earth yellow", hex: "#f1c649" },
            { name: "satin sheen", hex: "#f1e03c" },
            { name: "harvest gold", hex: "#f7d33f" },
            { name: "old gold", hex: "#f1ba37" },
            { name: "vegas gold", hex: "#f2db3f" },
            { name: "brass", hex: "#f6c72d" },
            { name: "yellow ochre", hex: "#f3e63a" },
            { name: "sandstorm", hex: "#f2d12c" },
            { name: "laguna", hex: "#f6c131" },
            { name: "laser lemon", hex: "#f3dd27" },
            { name: "unmellow", hex: "#f4cb2f" },
            { name: "royal yellow", hex: "#f6ec1f" },
            { name: "gargoyle", hex: "#f4d72a" },
            { name: "tuscan", hex: "#f4bf1c" },
            { name: "sunny", hex: "#f6e423" },
            { name: "pineapple", hex: "#f5cc17" },
            { name: "chiffon yellow", hex: "#f6b81f" },
        ],
        oranges: [
            { name: "orange neon", hex: "#ff6d4d" },
            { name: "orange", hex: "#ff794d" },
            { name: "tangerine", hex: "#f18660" },
            { name: "apricot", hex: "#eca765" },
            { name: "pumpkin", hex: "#ec9260" },
            { name: "coral", hex: "#f2b45f" },
            { name: "peach", hex: "#ec9b5c" },
            { name: "carrot", hex: "#ed8c63" },
            { name: "amber orange", hex: "#f1a651" },
            { name: "marmalade", hex: "#ed955e" },
            { name: "clementine", hex: "#ecb152" },
            { name: "burnt orange", hex: "#f39f54" },
            { name: "persimmon", hex: "#ec824e" },
            { name: "cantaloupe", hex: "#edaa55" },
            { name: "salmon orange", hex: "#f28c43" },
            { name: "papaya", hex: "#ed7c50" },
            { name: "mango", hex: "#ec9944" },
            { name: "copper", hex: "#f38546" },
            { name: "rust", hex: "#eda63f" },
            { name: "terracotta", hex: "#ee9247" },
            { name: "sienna", hex: "#f37034" },
            { name: "ochre orange", hex: "#ee9f42" },
            { name: "flame", hex: "#ed7f36" },
            { name: "tigers eye", hex: "#f5ae37" },
            { name: "carnelian", hex: "#ee8c31", nav: true },
            { name: "spanish orange", hex: "#ef7738" },
            { name: "princeton", hex: "#f59c25" },
            { name: "cadmium orange", hex: "#ef8433" },
            { name: "dark orange", hex: "#ee6127" },
            { name: "international orange", hex: "#f69328" },
            { name: "pumpkin spice", hex: "#ef7022" },
            { name: "gamboge", hex: "#f0a12a" },
            { name: "cheddar", hex: "#f57e17" },
            { name: "fulvous", hex: "#f06725" },
            { name: "bittersweet", hex: "#f08f18" },
            { name: "mandarin", hex: "#f5751b" },
            { name: "melon", hex: "#f04f13" },
            { name: "atomic tangerine", hex: "#f1851b" },
            { name: "deep saffron", hex: "#f45e0a" },
            { name: "alloy orange", hex: "#f19616" },
            { name: "xanthous orange", hex: "#ed710d" },
            { name: "giants orange", hex: "#f5540e" },
            { name: "dutch white", hex: "#e9820c" },
            { name: "ripe mango", hex: "#f1660c" },
            { name: "sunset orange", hex: "#e7930a" },
            { name: "ember", hex: "#ee780b" },
            { name: "harvest orange", hex: "#e2530b" },
            { name: "spice", hex: "#eb890a" },
            { name: "tawny", hex: "#de640a" },
            { name: "honey orange", hex: "#e7480a" },
        ],
        reds: [
            { name: "neon fire", hex: "#ff5e67" },
            { name: "rose", hex: "#ff4649" },
            { name: "neon red", hex: "#ff668c" },
            { name: "crimson", hex: "#de405a" },
            { name: "scarlet", hex: "#d84f46" },
            { name: "cherry", hex: "#d7414d" },
            { name: "ruby", hex: "#df563e" },
            { name: "brick", hex: "#d73d3c" },
            { name: "cardinal", hex: "#d94357" },
            { name: "garnet", hex: "#de402f" },
            { name: "maroon", hex: "#d93e45" },
            { name: "vermilion", hex: "#d74f31" },
            { name: "carmine", hex: "#e03932" },
            { name: "burgundy", hex: "#d72c3d" },
            { name: "firebrick", hex: "#d94833" },
            { name: "tomato", hex: "#de2022" },
            { name: "cinnabar", hex: "#d33226" },
            { name: "rosewood", hex: "#e1212e" },
            { name: "oxblood", hex: "#cf3f24" },
            { name: "sangria red", hex: "#d82825" },
            { name: "currant", hex: "#d31b31" },
            { name: "chili", hex: "#d43623" },
            { name: "candy apple", hex: "#c82026" },
            { name: "poppy", hex: "#d92e48", nav: true },
            { name: "fire engine", hex: "#d83f1a" },
            { name: "imperial red", hex: "#c4271f" },
            { name: "persian red", hex: "#cd202f" },
            { name: "english red", hex: "#c72f17" },
            { name: "indian red", hex: "#c91e1e" },
            { name: "madder", hex: "#bd1c32" },
            { name: "alabama crimson", hex: "#cc2516" },
            { name: "amaranth", hex: "#b91a23" },
            { name: "rusty red", hex: "#c2381b" },
            { name: "jasper", hex: "#bb1813" },
            { name: "chestnut red", hex: "#be1a2b" },
            { name: "auburn", hex: "#b12a17" },
            { name: "barn red", hex: "#bf1317" },
            { name: "blood", hex: "#ad162e" },
            { name: "claret", hex: "#b62117" },
            { name: "merlot", hex: "#ad111d" },
            { name: "raspberry red", hex: "#b22d15" },
            { name: "venetian red", hex: "#a51513" },
            { name: "turkey red", hex: "#b11126" },
            { name: "redwood", hex: "#a12012" },
            { name: "cordovan", hex: "#aa1319" },
            { name: "falu red", hex: "#9e2a10" },
            { name: "upsdell", hex: "#a61812" },
            { name: "rufous", hex: "#99101d" },
            { name: "lava", hex: "#a22310" },
            { name: "rojo", hex: "#950f10" },
        ],
        pinks: [
            { name: "pink", hex: "#e981e8" },
            { name: "pinkNeon", hex: "#ff83dd" },
            { name: "magenta", hex: "#d25ca4" },
            { name: "rose pink", hex: "#f1a7f1" },
            { name: "fuchsia", hex: "#eeaace" },
            { name: "bubblegum", hex: "#eea5e1" },
            { name: "salmon", hex: "#f2a6c1" },
            { name: "blush", hex: "#eda1d2" },
            { name: "flamingo", hex: "#efa8ea" },
            { name: "coral pink", hex: "#f199c2" },
            { name: "hot pink", hex: "#efa3dc" },
            { name: "rose petal", hex: "#ed98b0" },
            { name: "carnation", hex: "#f29bcd" },
            { name: "watermelon", hex: "#ed93e1" },
            { name: "cerise", hex: "#ee9abc" },
            { name: "punch", hex: "#f18ad1" },
            { name: "taffy", hex: "#ee95ec" },
            { name: "cotton candy", hex: "#ed89bc" },
            { name: "peony", hex: "#f28ddd" },
            { name: "raspberry", hex: "#ed84a7" },
            { name: "mauve pink", hex: "#ee8cc9" },
            { name: "dusty rose", hex: "#f17be6" },
            { name: "shell pink", hex: "#ee87b5" },
            { name: "piggy pink", hex: "#f27e9d" },
            { name: "baby pink", hex: "#ed7ace", nav: true },
            { name: "cameo", hex: "#ed75b7" },
            { name: "amaranth pink", hex: "#ee7ddc" },
            { name: "brink pink", hex: "#f26c9e" },
            { name: "french rose", hex: "#ee78c6" },
            { name: "mexican pink", hex: "#ed6be7" },
            { name: "persian pink", hex: "#f36eaf" },
            { name: "barbie pink", hex: "#ee66cf" },
            { name: "magenta pink", hex: "#ef6e95" },
            { name: "rose bonbon", hex: "#f35cb6" },
            { name: "paradise pink", hex: "#ef68df" },
            { name: "charm pink", hex: "#ee5c99" },
            { name: "tickle me", hex: "#f55ec8" },
            { name: "lavender rose", hex: "#ef56ed" },
            { name: "cyclamen", hex: "#f05eab" },
            { name: "thulian", hex: "#f44dd4" },
            { name: "ruby pink", hex: "#f0598e" },
            { name: "fandango pink", hex: "#f04cb4" },
            { name: "hollywood", hex: "#f450e7" },
            { name: "razzmatazz", hex: "#f04694" },
            { name: "wild strawberry", hex: "#f14ec8" },
            { name: "rose quartz", hex: "#f33f72" },
            { name: "orchid pink", hex: "#f248a9" },
            { name: "tea rose", hex: "#f13bd7" },
            { name: "pale pink", hex: "#f34288" },
            { name: "champagne pink", hex: "#f236b5" },
        ],
        browns: [
            { name: "chocolate", hex: "#c96540" },
            { name: "coffee", hex: "#c28147" },
            { name: "mocha", hex: "#c16e42" },
            { name: "chestnut", hex: "#ca8c3f" },
            { name: "walnut", hex: "#bf753e" },
            { name: "mahogany", hex: "#c46b45" },
            { name: "umber", hex: "#c37c34" },
            { name: "tan", hex: "#c3713f" },
            { name: "khaki", hex: "#b78239" },
            { name: "caramel", hex: "#c97734" },
            { name: "toffee", hex: "#b45f36" },
            { name: "espresso", hex: "#bd7f39" },
            { name: "hazelnut", hex: "#b6652d" },
            { name: "cocoa", hex: "#b95b36" },
            { name: "sepia", hex: "#ac6d32" },
            { name: "russet", hex: "#bd602d" },
            { name: "bronze", hex: "#a87330" },
            { name: "taupe", hex: "#b26932" },
            { name: "fawn", hex: "#aa4f27" },
            { name: "beige", hex: "#ad7030" },
            { name: "sand", hex: "#9f582b" },
            { name: "camel", hex: "#b07827" },
            { name: "wheat", hex: "#9b5e29" },
            { name: "cinnamon", hex: "#a5552b" },
            { name: "raw sienna", hex: "#8e4b23", nav: true },
            { name: "nutmeg", hex: "#9d6522" },
            { name: "clay", hex: "#a15b29" },
            { name: "earth", hex: "#934525" },
            { name: "bistre", hex: "#a36222" },
            { name: "burnt umber", hex: "#996825" },
            { name: "van dyke", hex: "#8f501c" },
            { name: "seal brown", hex: "#944824" },
            { name: "liver", hex: "#865520" },
            { name: "chamoisee", hex: "#954c1c" },
            { name: "wenge", hex: "#81391e" },
            { name: "beaver", hex: "#8b5320" },
            { name: "shadow", hex: "#803d18" },
            { name: "field drab", hex: "#87581e" },
            { name: "dark tan", hex: "#78431a" },
            { name: "desert sand", hex: "#853a19" },
            { name: "ecru", hex: "#744719" },
            { name: "buff", hex: "#7e401b" },
            { name: "almond", hex: "#714b15" },
            { name: "biscuit", hex: "#794519" },
            { name: "pecan", hex: "#6a3216" },
            { name: "pralin\u00c3\u00a9", hex: "#764a16" },
            { name: "gingerbread", hex: "#653514" },
            { name: "molasses", hex: "#702f16" },
            { name: "peanut", hex: "#613912" },
            { name: "driftwood", hex: "#6b3414" },
        ],
        greys: [
            { name: "cool grey", hex: "#a9b1d6" },
            { name: "moonlight", hex: "#9fb4df" },
            { name: "silver", hex: "#c0caf5" },
            { name: "ash", hex: "#c0c7ce" },
            { name: "slate grey", hex: "#c3c6ca" },
            { name: "charcoal", hex: "#bdc1c5" },
            { name: "gunmetal", hex: "#c0c3ce" },
            { name: "pewter", hex: "#b7bbc0" },
            { name: "steel", hex: "#c2c6ca" },
            { name: "fog", hex: "#aeb3bf" },
            { name: "dove", hex: "#bcbfc5" },
            { name: "nickel", hex: "#abaeb6" },
            { name: "graphite grey", hex: "#b3b8c3" },
            { name: "smoke grey", hex: "#a5abb1" },
            { name: "stone grey", hex: "#b0b2bb" },
            { name: "concrete", hex: "#9ba3b0" },
            { name: "cement", hex: "#a9afb6" },
            { name: "platinum", hex: "#999da8" },
            { name: "gainsboro", hex: "#a0a8b4" },
            { name: "silver grey", hex: "#9296a3" },
            { name: "battleship", hex: "#9da2ac" },
            { name: "dim grey", hex: "#8894a2" },
            { name: "davy grey", hex: "#979ba7" },
            { name: "cadet grey", hex: "#868d99" },
            { name: "cool gray", hex: "#8d92a6", nav: true },
            { name: "gray", hex: "#7f8694" },
            { name: "taupe grey", hex: "#8a939e" },
            { name: "payne grey", hex: "#767d93" },
            { name: "onyx grey", hex: "#848c99" },
            { name: "iron", hex: "#737e8b" },
            { name: "shadow grey", hex: "#7b8397" },
            { name: "granite", hex: "#6e7785" },
            { name: "flint", hex: "#777d8f" },
            { name: "pebble", hex: "#666f82" },
            { name: "cloud", hex: "#717d8a" },
            { name: "mist grey", hex: "#636979" },
            { name: "overcast", hex: "#6a7587" },
            { name: "aluminum", hex: "#5e6974" },
            { name: "tungsten", hex: "#666e7f" },
            { name: "zinc", hex: "#57616f" },
            { name: "lead", hex: "#616779" },
            { name: "seal grey", hex: "#535b68" },
            { name: "trout", hex: "#5b6774" },
            { name: "manatee", hex: "#4e5462" },
            { name: "cinereous", hex: "#57606d" },
            { name: "rocket grey", hex: "#494d5c" },
            { name: "quick silver", hex: "#525967" },
            { name: "spanish gray", hex: "#444c56" },
            { name: "sonic silver", hex: "#4c5261" },
            { name: "old silver", hex: "#3f4550" },
        ],
        whites: [
            { name: "white", hex: "#ffffff" },
            { name: "pearl", hex: "#fbfaf9" },
            { name: "alabaster", hex: "#f9f9f7" },
            { name: "snow", hex: "#fafaf8" },
            { name: "ivory", hex: "#f8f7f5" },
            { name: "cream", hex: "#f9f8f6" },
            { name: "egg shell", hex: "#f7f6f2" },
            { name: "cotton", hex: "#f7f7f4" },
            { name: "chiffon", hex: "#f5f5f1" },
            { name: "salt", hex: "#f7f6f1" },
            { name: "lace", hex: "#f4f2ee" },
            { name: "coconut", hex: "#f5f4f0" },
            { name: "linen", hex: "#f3f2eb" },
            { name: "bone", hex: "#f3f1ee" },
            { name: "daisy", hex: "#f1f0ea" },
            { name: "powder", hex: "#f3f1eb" },
            { name: "frost", hex: "#f0efe8" },
            { name: "porcelain", hex: "#f1efe9" },
            { name: "parchment", hex: "#efece5" },
            { name: "rice", hex: "#f0efe7" },
            { name: "seashell", hex: "#edebe3" },
            { name: "vanilla", hex: "#efeee4" },
            { name: "milk", hex: "#ecebe1" },
            { name: "chalk", hex: "#edeae2" },
            { name: "ghost white", hex: "#ebeade", nav: true },
        ],
        blacks: [
            { name: "black", hex: "#000000" },
            { name: "obsidian", hex: "#272c35" },
            { name: "onyx", hex: "#2a2a32" },
            { name: "jet", hex: "#27292f" },
            { name: "ebony", hex: "#272634" },
            { name: "charcoal black", hex: "#24252c" },
            { name: "raven", hex: "#26282e" },
            { name: "coal", hex: "#201f2b" },
            { name: "ink", hex: "#23242b" },
            { name: "pitch", hex: "#201e26" },
            { name: "soot", hex: "#1e1f2a" },
            { name: "midnight", hex: "#1c1e23" },
            { name: "shadow black", hex: "#1e1d25" },
            { name: "void", hex: "#181921" },
            { name: "carbon black", hex: "#1b1d22" },
            { name: "tar", hex: "#16161d" },
            { name: "licorice", hex: "#171920" },
            { name: "sable", hex: "#14141a" },
            { name: "vantablack", hex: "#15161c" },
            { name: "graphite black", hex: "#111217" },
            { name: "eclipse", hex: "#131319" },
            { name: "abyss", hex: "#0f0f14" },
            { name: "noir", hex: "#111016" },
            { name: "crow", hex: "#0c0c10" },
            { name: "oil", hex: "#0d0f13", nav: true },
        ],
    },
};
