export const DATA = {
    order: [
        "purples",
        "blues",
        "greens",
        "yellows",
        "oranges",
        "reds",
        "pinks",
        "earthy",
        "neutrals",
    ],
    labels: {
        purples: "Purples",
        blues: "Blues",
        greens: "Greens",
        yellows: "Yellows",
        oranges: "Oranges",
        reds: "Reds",
        pinks: "Pinks",
        earthy: "Earthy",
        neutrals: "Neutrals",
    },
    families: {
        purples: [
            { name: "dark purple", hex: "#30235a" },
            { name: "pinot noir", hex: "#220835" },
            { name: "smoke purple", hex: "#341e73" },
            { name: "purple", hex: "#3918a4" },
            { name: "lilac", hex: "#4e11c0" },
            { name: "violet", hex: "#6b4ec5" },
            { name: "lavender", hex: "#8869e2" },
            { name: "mauve", hex: "#9058ea" },
            { name: "boysenberry", hex: "#140340" },
            { name: "plum", hex: "#2d1d4c" },
            { name: "grape", hex: "#55249f" },
            { name: "periwinkle mist", hex: "#5e15c3" },
            { name: "iris", hex: "#7108eb" },
            { name: "orchid", hex: "#a368d6" },
            { name: "amethyst", hex: "#a165dc" },
            { name: "eggplant", hex: "#300d5b" },
            { name: "wine", hex: "#3c2357" },
            { name: "mulberry", hex: "#4d1d6d" },
            { name: "raisin", hex: "#671bb5" },
            { name: "heather", hex: "#8914cc" },
            { name: "thistle", hex: "#9457be" },
            { name: "wisteria", hex: "#b68ddc" },
            { name: "byzantium", hex: "#280b37" },
            { name: "tyrian", hex: "#4d0e7e" },
            { name: "grape soda", hex: "#762f98", nav: true },
            { name: "royal purple", hex: "#672392" },
            { name: "ube", hex: "#9827c9" },
            { name: "mountbatten", hex: "#b54af0" },
            { name: "pomp", hex: "#c18dd1" },
            { name: "pansy", hex: "#cf9fe6" },
            { name: "african violet", hex: "#64167c" },
            { name: "electric purple", hex: "#770ba3" },
            { name: "veronica", hex: "#69307c" },
            { name: "phlox", hex: "#9029b7" },
            { name: "dark orchid", hex: "#c432e3" },
            { name: "purple heart", hex: "#e84df8" },
            { name: "medium purple", hex: "#c984d0" },
            { name: "fandango", hex: "#4c0f51" },
            { name: "mardi gras", hex: "#8a0fa4" },
            { name: "dark magenta", hex: "#b600d8" },
            { name: "imperial", hex: "#96339e" },
            { name: "regalia", hex: "#c224de" },
            { name: "russian violet", hex: "#ea62ec" },
            { name: "persian indigo", hex: "#c688c7" },
            { name: "tekhelet", hex: "#411741" },
            { name: "majorelle", hex: "#851484" },
            { name: "blue violet", hex: "#9d08a0" },
            { name: "han purple", hex: "#97459b" },
            { name: "violet blue", hex: "#c041c3" },
            { name: "xanadu", hex: "#dc50d1" },
            { name: "glossy grape", hex: "#fa6de5" },
        ],
        blues: [
            { name: "night sky", hex: "#051626" },
            { name: "galaxy blue", hex: "#001122" },
            { name: "dark blue", hex: "#101628" },
            { name: "midnight blue", hex: "#0d1b2f" },
            { name: "navy", hex: "#112038" },
            { name: "indigo", hex: "#172741" },
            { name: "graphite", hex: "#141a2e" },
            { name: "dark teal", hex: "#182626" },
            // { name: "dark slate", hex: "#3b4261" },
            // { name: "slate", hex: "#586e98" },
            // { name: "smoke", hex: "#737aa2" },
            // { name: "stone", hex: "#5d82be" },
            { name: "denim", hex: "#4673bc" },
            { name: "periwinkle", hex: "#7aa2f7" },
            { name: "cobalt", hex: "#5aa8ff" },
            { name: "ocean", hex: "#4da0ff" },
            { name: "sky blue", hex: "#00aeff" },
            { name: "arctic", hex: "#7dcfff" },
            { name: "cyan", hex: "#66d4ff" },
            { name: "bright cyan", hex: "#00d7ff" },
            { name: "teal", hex: "#2ac3de" },
            { name: "aqua", hex: "#0db9d7" },
            { name: "jade", hex: "#26a1ba" },
            { name: "lagoon", hex: "#027bce" },
            { name: "sargasso", hex: "#034078" },
            { name: "cerulean", hex: "#2d8de3" },
            { name: "sapphire", hex: "#289eff" },
            { name: "peacock", hex: "#04c5d9" },
            { name: "lapis", hex: "#00a6fb" },
            { name: "spruce", hex: "#0f387c" },
            { name: "admiral", hex: "#0531a6" },
            { name: "cornflower", hex: "#2d4e9c" },
            { name: "steel blue", hex: "#2556da" },
            { name: "azure", hex: "#4685ff" },
            { name: "powder blue", hex: "#3a6bf5" },
            { name: "baby blue", hex: "#8296da" },
            { name: "cadet", hex: "#026174" },
            { name: "prussian blue", hex: "#021e44" },
            { name: "phthalo blue", hex: "#0c0040" },
            { name: "electric blue", hex: "#1e419a" },
            { name: "royal blue", hex: "#0466c8", nav: true },
            { name: "", hex: "#1b5b6a" },
            { name: "yale blue", hex: "#1d276e" },
            { name: "air force", hex: "#141a7e" },
            { name: "glaucous", hex: "#1580b9" },
            { name: "tufts blue", hex: "#4d50b8" },
            { name: "celestial", hex: "#1d276e" },
            { name: "bleu de france", hex: "#123b9a" },
            { name: "iceberg", hex: "#8ad7ff" },
        ],
        greens: [
            { name: "neon mint", hex: "#00ffaf" },
            { name: "lime", hex: "#7dfb89" },
            { name: "lime neon", hex: "#65ff74", nav: true },
            { name: "chartreuse", hex: "#72f318" },
            { name: "bottle green", hex: "#42db9e" },
            { name: "aquamarine", hex: "#00fbee" },
            { name: "sacramento", hex: "#45f5b6" },
            { name: "mint", hex: "#2fe1c8" },
            { name: "spring green", hex: "#7ad445" },
            { name: "kelly green", hex: "#92e662" },
            { name: "emerald", hex: "#39f06b" },
            { name: "jade green", hex: "#28d67b" },
            { name: "pine", hex: "#5de220" },
            { name: "sage", hex: "#3ec280" },
            { name: "olive drab", hex: "#37842e" },
            { name: "viridian", hex: "#3bb325" },
            { name: "fern", hex: "#74de59" },
            { name: "moss", hex: "#24690d" },
            { name: "shamrock", hex: "#37842e" },
            { name: "malachite", hex: "#3e892a" },
            { name: "lime zest", hex: "#38a408" },
            { name: "seafoam", hex: "#4efd78" },
            { name: "seaweed", hex: "#5dc154" },
            { name: "pistachio", hex: "#88ca5a" },
            { name: "avocado", hex: "#7ae582" },
            { name: "hunter green", hex: "#12af17" },
            { name: "juniper", hex: "#389231" },
            { name: "basil", hex: "#26c826" },
            { name: "clover", hex: "#25e024" },
            { name: "laurel", hex: "#34ec33" },
            { name: "celadon", hex: "#64cc72" },
            { name: "tea green", hex: "#9fffcb" },
            { name: "mantis", hex: "#107a27" },
            { name: "harlequin", hex: "#04b31e" },
            { name: "asparagus", hex: "#1e7d12" },
            { name: "screamin green", hex: "#3caf4a" },
            { name: "neon green", hex: "#30d155" },
            { name: "june bud", hex: "#39f06b" },
            { name: "artichoke", hex: "#76db98" },
            { name: "brunswick", hex: "#129340" },
            { name: "castleton", hex: "#04da45" },
            { name: "myrtle", hex: "#4ac771" },
            { name: "phthalo green", hex: "#3de572" },
            { name: "hooker green", hex: "#42f68d" },
            { name: "jungle green", hex: "#71d293" },
            { name: "army green", hex: "#197046" },
            { name: "dark moss", hex: "#23a958" },
            { name: "reseda", hex: "#11ad66" },
            { name: "dartmouth", hex: "#17943c" },
            { name: "feldgrau green", hex: "#33d899" },
        ],
        yellows: [
            { name: "gold", hex: "#d9b24f" },
            { name: "sun", hex: "#dba52e" },
            { name: "lemon", hex: "#e8b13e" },
            { name: "canary", hex: "#ffd75c" },
            { name: "mustard", hex: "#e6cd8a" },
            { name: "amber", hex: "#eed99f" },
            { name: "honey", hex: "#f2da80" },
            { name: "daffodil", hex: "#f7ae00" },
            { name: "goldenrod", hex: "#dfba28" },
            { name: "indian yellow", hex: "#ffb800" },
            { name: "butter", hex: "#f1c54c" },
            { name: "dandelion", hex: "#ffd875" },
            { name: "flax", hex: "#e8d79a" },
            { name: "maize", hex: "#f3e38c" },
            { name: "sunflower", hex: "#ffd522", nav: true },
            { name: "chrome yellow", hex: "#ceb750" },
            { name: "cadmium yellow", hex: "#e3cf49" },
            { name: "school bus", hex: "#f0db3d" },
            { name: "banana", hex: "#f4ce4c" },
            { name: "cream yellow", hex: "#e6dc8f" },
            { name: "citrine", hex: "#eae38a" },
            { name: "yellow ochre", hex: "#c79b00" },
            { name: "cadmium yellow", hex: "#ffec00" },
            { name: "mikado", hex: "#d7b744" },
            { name: "aureolin", hex: "#ebd470" },
            { name: "naples yellow", hex: "#f1e373" },
            { name: "straw", hex: "#f6df6c" },
            { name: "sunglow", hex: "#e7df89" },
            { name: "icterine", hex: "#f4ee97" },
            { name: "hansa", hex: "#e9e217" },
            { name: "meat brown", hex: "#ffeb36" },
            { name: "arylide", hex: "#ddd159" },
            { name: "trombone", hex: "#ebdc70" },
            { name: "earth yellow", hex: "#f0ef6d" },
            { name: "satin sheen", hex: "#fffe68" },
            { name: "harvest gold", hex: "#f3eebb" },
            { name: "old gold", hex: "#eed53a" },
            { name: "vegas gold", hex: "#f5e44b" },
            { name: "brass", hex: "#ffec45" },
            { name: "yellow ochre", hex: "#e2d36e" },
            { name: "sandstorm", hex: "#f4e566" },
            { name: "laguna", hex: "#faf085" },
            { name: "laser lemon", hex: "#e9e4a9" },
            { name: "unmellow", hex: "#d6db53" },
            { name: "royal yellow", hex: "#e9f04c" },
            { name: "gargoyle", hex: "#fef74e" },
            { name: "tuscan", hex: "#d9db66" },
            { name: "sunny", hex: "#e7ea5f" },
            { name: "pineapple", hex: "#f3ef76" },
            { name: "chiffon yellow", hex: "#f8f07a" },
        ],
        oranges: [
            { name: "orange neon", hex: "#c13e16" },
            { name: "orange", hex: "#f6732d", nav: true },
            { name: "tangerine", hex: "#f0632c" },
            { name: "apricot", hex: "#fe7b23" },
            { name: "pumpkin", hex: "#e58458" },
            { name: "coral", hex: "#ef8b59" },
            { name: "peach", hex: "#f08c51" },
            { name: "carrot", hex: "#fe6401" },
            { name: "amber orange", hex: "#d85823" },
            { name: "marmalade", hex: "#e77f35" },
            { name: "clementine", hex: "#f3803d" },
            { name: "burnt orange", hex: "#ff6a23" },
            { name: "persimmon", hex: "#e48c58" },
            { name: "cantaloupe", hex: "#eea464" },
            { name: "salmon orange", hex: "#c7570b" },
            { name: "papaya", hex: "#d07426" },
            { name: "mango", hex: "#e0863d" },
            { name: "copper", hex: "#ed9741" },
            { name: "rust", hex: "#f58a28" },
            { name: "terracotta", hex: "#e18d57" },
            { name: "sienna", hex: "#eda263" },
            { name: "ochre orange", hex: "#d66313" },
            { name: "flame", hex: "#de6f0b" },
            { name: "tigers eye", hex: "#e49731" },
            { name: "carnelian", hex: "#e88d3c" },
            { name: "spanish orange", hex: "#f38919" },
            { name: "princeton", hex: "#f7a038" },
            { name: "cadmium orange", hex: "#eca658" },
            { name: "dark orange", hex: "#f0c086" },
            { name: "international orange", hex: "#f27e0d" },
            { name: "pumpkin spice", hex: "#fb9912" },
            { name: "gamboge", hex: "#ea872f" },
            { name: "cheddar", hex: "#e9a03c" },
            { name: "fulvous", hex: "#f3a22c" },
            { name: "bittersweet", hex: "#ffa037" },
            { name: "mandarin", hex: "#ecb05b" },
            { name: "melon", hex: "#eba421" },
            { name: "atomic tangerine", hex: "#ef890b" },
            { name: "deep saffron", hex: "#fe9811" },
            { name: "alloy orange", hex: "#eba02e" },
            { name: "xanthous orange", hex: "#f3a23d" },
            { name: "giants orange", hex: "#fcb357" },
            { name: "dutch white", hex: "#e8bb60" },
            { name: "ripe mango", hex: "#e2aa23" },
            { name: "sunset orange", hex: "#ebb310" },
            { name: "ember", hex: "#fcb815" },
            { name: "harvest orange", hex: "#dfa64d" },
            { name: "spice", hex: "#ecb460" },
            { name: "tawny", hex: "#efbf3e" },
            { name: "honey orange", hex: "#fdc94a" },
        ],
        reds: [
            { name: "neon fire", hex: "#751c33" },
            { name: "rose", hex: "#b4223b" },
            { name: "neon red", hex: "#e2112d" },
            { name: "crimson", hex: "#cb0923" },
            { name: "scarlet", hex: "#c63741" },
            { name: "cherry", hex: "#e53757" },
            { name: "ruby", hex: "#f1606f" },
            { name: "brick", hex: "#b30808" },
            { name: "cardinal", hex: "#e8303c", nav: true },
            { name: "garnet", hex: "#b31d31" },
            { name: "maroon", hex: "#c21325" },
            { name: "vermilion", hex: "#ff261f" },
            { name: "carmine", hex: "#d53c39" },
            { name: "burgundy", hex: "#db3e46" },
            { name: "firebrick", hex: "#9b0c10" },
            { name: "tomato", hex: "#9c3232" },
            { name: "cinnabar", hex: "#a52022" },
            { name: "rosewood", hex: "#ec1c20" },
            { name: "oxblood", hex: "#f91d27" },
            { name: "sangria red", hex: "#f25c54" },
            { name: "currant", hex: "#da3f36" },
            { name: "chili", hex: "#781712" },
            { name: "candy apple", hex: "#bc240d" },
            { name: "poppy", hex: "#97302c" },
            { name: "fire engine", hex: "#c72b29" },
            { name: "imperial red", hex: "#e2422a" },
            { name: "persian red", hex: "#e62913" },
            { name: "english red", hex: "#e37562" },
            { name: "indian red", hex: "#e38475" },
            { name: "madder", hex: "#880e09" },
            { name: "alabama crimson", hex: "#ac2d07" },
            { name: "amaranth", hex: "#bf392f" },
            { name: "rusty red", hex: "#d74633" },
            { name: "jasper", hex: "#e22f1a" },
            { name: "chestnut red", hex: "#f33018" },
            { name: "auburn", hex: "#d86e63" },
            { name: "alizarin crimson", hex: "#4e1500" },
            { name: "blood", hex: "#ac1e06" },
            { name: "claret", hex: "#d33203" },
            { name: "merlot", hex: "#bc391d" },
            { name: "raspberry red", hex: "#e54419" },
            { name: "venetian red", hex: "#ec644b" },
            { name: "turkey red", hex: "#db967d" },
            { name: "redwood", hex: "#78371a" },
            { name: "cordovan", hex: "#ae4d16" },
            { name: "falu red", hex: "#dc3e04" },
            { name: "upsdell", hex: "#ca6b34" },
            { name: "rufous", hex: "#cf522d" },
            { name: "lava", hex: "#f05a1f" },
            { name: "rojo", hex: "#fc8243" },
        ],
        pinks: [
            { name: "pink", hex: "#c839c1" },
            { name: "pinkNeon", hex: "#d84bce" },
            { name: "magenta", hex: "#eb37e3" },
            { name: "rose pink", hex: "#f868ed" },
            { name: "fuchsia", hex: "#e068e1" },
            { name: "bubblegum", hex: "#ee97e2" },
            { name: "salmon", hex: "#f07aea" },
            { name: "blush", hex: "#f409cd" },
            { name: "flamingo", hex: "#cb44c0" },
            { name: "coral pink", hex: "#e55cce" },
            { name: "hot pink", hex: "#f66fe9" },
            { name: "rose petal", hex: "#fd73de" },
            { name: "carnation", hex: "#e074d1" },
            { name: "watermelon", hex: "#ec7cce" },
            { name: "cerise", hex: "#f21dc1" },
            { name: "punch", hex: "#ce35b1" },
            { name: "taffy", hex: "#e55cb8" },
            { name: "cotton candy", hex: "#e74caf" },
            { name: "peony", hex: "#f870cf" },
            { name: "raspberry", hex: "#de70bd" },
            { name: "mauve pink", hex: "#e491c8" },
            { name: "dusty rose", hex: "#e1459d" },
            { name: "shell pink", hex: "#f40d8e" },
            { name: "piggy pink", hex: "#d2459b" },
            { name: "baby pink", hex: "#e077b9" },
            { name: "cameo", hex: "#f471b3" },
            { name: "amaranth pink", hex: "#f374b9" },
            { name: "brink pink", hex: "#e27caf" },
            { name: "french rose", hex: "#f0b8da" },
            { name: "mexican pink", hex: "#ff5ebb", nav: true },
            { name: "persian pink", hex: "#f02e80" },
            { name: "barbie pink", hex: "#d05b8d" },
            { name: "magenta pink", hex: "#eb57a6" },
            { name: "rose bonbon", hex: "#f38fbb" },
            { name: "paradise pink", hex: "#fb7cad" },
            { name: "charm pink", hex: "#e98ab4" },
            { name: "tickle me", hex: "#db2e6d" },
            { name: "lavender rose", hex: "#ea4584" },
            { name: "cyclamen", hex: "#f23485" },
            { name: "thulian", hex: "#e56b9d" },
            { name: "ruby pink", hex: "#ed618a" },
            { name: "fandango pink", hex: "#f47f9a" },
            { name: "hollywood", hex: "#eaafc0" },
            { name: "razzmatazz", hex: "#dc3369" },
            { name: "wild strawberry", hex: "#ee507e" },
            { name: "rose quartz", hex: "#f2617a" },
            { name: "orchid pink", hex: "#e27b8c" },
            { name: "tea rose", hex: "#e88792" },
            { name: "pale pink", hex: "#f08392" },
            { name: "champagne pink", hex: "#fb8399" },
        ],
        earthy: [
            { name: "dark teal", hex: "#182626" },
            { name: "forest", hex: "#183a41" },
            { name: "sap green", hex: "#0a3410" },
            { name: "phthalo green", hex: "#102e3c" },
            { name: "coffee", hex: "#764229" },
            { name: "mocha", hex: "#763f1e" },
            { name: "walnut", hex: "#9f5f46" },
            { name: "mahogany", hex: "#ae6143" },
            { name: "umber", hex: "#cb8758" },
            { name: "dark sienna", hex: "#5f2e1f" },
            { name: "khaki", hex: "#80512d" },
            { name: "caramel", hex: "#915228" },
            { name: "toffee", hex: "#934625" },
            { name: "espresso", hex: "#b65821" },
            { name: "hazelnut", hex: "#a26b49" },
            { name: "cocoa", hex: "#492511" },
            { name: "russet", hex: "#2c3325", nav: true },
            { name: "van dyke brown", hex: "#221b15" },
            { name: "bronze", hex: "#6f4b32" },
            { name: "taupe", hex: "#945930" },
            { name: "fawn", hex: "#b3662c" },
            { name: "sand", hex: "#c58c5b" },
            { name: "camel", hex: "#6a441a" },
            { name: "wheat", hex: "#613517" },
            { name: "cinnamon", hex: "#7b5532" },
            { name: "nutmeg", hex: "#955729" },
            { name: "clay", hex: "#d08c28" },
            { name: "bistre", hex: "#d29b63" },
            { name: "burnt umber", hex: "#593c16" },
            { name: "desert sand", hex: "#8c723a" },
        ],
        neutrals: [
            { name: "white", hex: "#ffffff" },
            { name: "nickel", hex: "#95a2bd" },
            { name: "grey", hex: "#818898" },
            { name: "pearl", hex: "#e2f1fb" },
            { name: "snow", hex: "#def2f4" },
            { name: "frost", hex: "#d2e9f9" },
            { name: "porcelain", hex: "#f8f8f7" },
            { name: "parchment", hex: "#f3f2ec" },
            { name: "vanilla", hex: "#fffbdb" },
            { name: "chalk", hex: "#eaeae8" },
            { name: "ghost white", hex: "#f9f9f6" },
            { name: "ivory", hex: "#e1dfdc" },
            { name: "cream", hex: "#f4f2ee" },
            { name: "pewter", hex: "#bcb8b1" },
            { name: "cloud", hex: "#9fa4c4" },
            { name: "mist", hex: "#babbc7" },
            { name: "ash", hex: "#7184a0" },
            { name: "raincloud", hex: "#2c3d55", nav: true },
            { name: "ink", hex: "#1b1c27" },
            { name: "overcast", hex: "#46485e" },
            { name: "quicksilver", hex: "#767692" },
            { name: "aluminum", hex: "#4b5173" },
            { name: "coal", hex: "#0f0f18" },
            { name: "pitch", hex: "#151421" },
            { name: "steel", hex: "#5a5f68" },
            { name: "shadow", hex: "#16151b" },
            { name: "black", hex: "#000000" },
            { name: "obsidian", hex: "#141722" },
            { name: "onyx", hex: "#17191e" },
            { name: "ebony", hex: "#111218" },
            { name: "charcoal", hex: "#232635" },
            { name: "raven", hex: "#242533" },
            { name: "void", hex: "#000714" },
            { name: "carbon", hex: "#14121a" },
            { name: "tar", hex: "#1e1c23" },
            { name: "eclipse", hex: "#090216" },
            { name: "jet", hex: "#0a080c" },
            { name: "noir", hex: "#05080b" },
        ],
    },
};
